### ISSUE TITLE
podman zfs, ubuntu 20.04.3

### ISSUE THREAD

**Issue by shaun-lloyd** [jwillikers/blog#21]
I have been having trouble getting podman working as per your instructions:

with storage.conf:
[storage]
driver = "zfs"

podman error=

ERRO[0000] User-selected graph driver "zfs" overwritten by graph driver "overlay" from database - delete libpod local files to resolve 
Error: 'overlay' is not supported over zfs, a mount_program is required: backing file system is unsupported for this graph driver

I have tried numerous mount_program, overlay. I am doing something wrong or is it broken again as the web is filled with statement "zfs is not supported" which leads me to believe it may be "buggy" with zfs, ergo not my fault.

Or am i am moron as i suspect and being a podman newbie am not seeing the obvious issue.

Thank you so much,

I just love all your articles / tutorial, but frustrating as hell not being able to do them without running podman ;(

**Comment by jwillikers** [comment]
@shaun-lloyd Thanks for the support! When changing the storage driver, Podman needs to be reset. What happens if you try running `podman system reset`? That will delete everything in Podman for your user, i.e. images and volumes, fyi.

**Comment by jwillikers** [comment]
Also, you might check that you have the [zfsutils-linux](https://packages.ubuntu.com/focal/zfsutils-linux) package installed. I think that package provides the fuse driver for ZFS.

**Comment by shaun-lloyd** [comment]
Thank you so much for getting back to me.I updated to 22.04.3, apt podman install no problem. With zfsonroot.Vagrant and VirtualBox were in the mix wanted different versions it was a nightmare, I could get 2 of any working but not all 3. Very annoying.I apologise I think just me being newbie got super confusing. Really appreciate your getting back have a great dayOn 15 Jan 2024 12:32 am, Jordan Williams ***@***.***> wrote:
Also, you might check that you have the zfsutils-linux package installed. I think that package provides the fuse driver for ZFS.

**Comment by jwillikers** [comment]
Yeah, it all gets pretty confusing, especially if you throw virtual machines and containers into the mix. Hopefully you'll get it figured out soon. [Practical ZFS](https://discourse.practicalzfs.com/) would also be a good place to reach out for help.

**Comment by shaun-lloyd** [comment]
Thankyou so much. Zfs is so amazing I get the cddl licensed issues and not invented here for Linux it's just a shame Linux hasn't/won't imbrace zfs 100%Really appreciate all your resources and willingness to help out.I've never lost a bit since I put my data on zfs about 5 years now, I trust it completely.On 18 Jan 2024 1:06 am, Jordan Williams ***@***.***> wrote:
Yeah, it all gets pretty confusing, especially if you throw virtual machines and containers into the mix. Hopefully you'll get it figured out soon. Practical ZFS would also be a good place to reach out for help.
