### ISSUE TITLE
[Backup Snapper Snapshots] and [Automount Encrypted System Volume]: Add `$` to command.

### ISSUE THREAD

**Issue by p4p4j0hn** [jwillikers/blog#22]
In the [Backup Snapper Snapshots](https://github.com/jwillikers/blog/blob/main/_posts/2021-02-27-Backup%20Snapper%20Snapshots%20With%20snap-sync.adoc) article, the following command fails.
``` bash
sudo snap-sync -c root \
  --UUID (sudo blkid -o value -s UUID /dev/mapper/backup_crypt) \
  --subvolid (sudo btrfs subvolume show /run/media/system/System_Backups \
    | awk -F ":[ \t]*" '/Subvolume ID:/ {gsub(//,""); print $2}')
```
This should have $ signs for the nested commands.
``` bash
sudo snap-sync -c root \
  --UUID $(sudo blkid -o value -s UUID /dev/mapper/backup_crypt) \
  --subvolid $(sudo btrfs subvolume show /run/media/system/System_Backups \
    | awk -F ":[ \t]*" '/Subvolume ID:/ {gsub(//,""); print $2}')
```
In [Automount Encrypted System Volume](https://github.com/jwillikers/blog/blob/main/_posts/2021-02-25-Automount%20an%20Encrypted%20System%20Volume.adoc)
``` bash
echo "backup_crypt UUID="(sudo blkid -o value -s UUID /dev/sdb1)" /etc/cryptsetup-keys.d/backup_crypt.key luks,noauto,nofail,discard" \
  | sudo tee -a /etc/crypttab
```
Should be:
``` bash
echo "backup_crypt UUID="$(sudo blkid -o value -s UUID /dev/sdb1)" /etc/cryptsetup-keys.d/backup_crypt.key luks,noauto,nofail,discard" \
  | sudo tee -a /etc/crypttab
```

**Comment by jwillikers** [comment]
Thanks! Since I use fish, I left out the `$` sign, but fish actually added compatibility for `$()` a while ago, so I can totally add that.

**Comment by p4p4j0hn** [comment]
Thanks :-) I really like your blog, especially the one-liner shell commands you put together.
